[master]
host = 127.0.0.1
port = 3306
user = test
password = testpwd

[backup]
host = 127.0.0.1
port = 3306
user = test
password = testpwd

[common]
database = testdb
tableSize = 10000
processCount = 32
execCount = 10000